# .github/workflows/hello-action-workflow.yml
name: Hello Action

on: [push]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hello Action
        uses: ./.github/actions/hello-action
